version: '3.4'

services:
  savingsplatform.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - DAPR_HTTP_PORT=3605
      - SimulationConfig__SpeedMultiplier=1
      - NAMESPACE=savingsplatform
      - StateStore__StateStoreName=statestore-postgres
      - ConnectionStrings__DocumentStore=host='postgres';username='postgres';password='example';port='5432';database='doc-store'
    ports:
      - "5136:80"

  savingsplatform.dashboard:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - DAPR_HTTP_PORT=3608
      - SimulationConfig__SpeedMultiplier=1
      - NAMESPACE=savingsplatform
    ports:
      - "5165:80"

  savingsplatform.eventstore:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - DAPR_HTTP_PORT=3606
      - ConnectionStrings__DocumentStore=host='postgres';username='postgres';password='example';port='5432';database='event-store'
      - NAMESPACE=savingsplatform
    ports:
      - "5163:80"

  savingsplatform.paymentproxy:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - DAPR_HTTP_PORT=3607
      - NAMESPACE=payments
      - StateStore__StateStoreName=statestore-payments
      - ProxyCfg__SavingsPlatformAppName=dapr-savings-acc
    ports:
      - "5161:80"
  
  savingsplatform.api-dapr:
    command: ["./daprd",
      "--app-id", "dapr-savings-acc",
      "--app-port", "80",
      "--dapr-http-port", "3605",
      "--placement-host-address", "placement:50000",
      "--resources-path", "/components",
      "-config", "/configuration/config.yaml"
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration:/configuration"
  
  savingsplatform.eventstore-dapr:
    command: ["./daprd",
      "--app-id", "dapr-savings-evt",
      "--app-port", "80",
      "--dapr-http-port", "3606",
      "--placement-host-address", "placement:50000",
      "--resources-path", "/components",
      "-config", "/configuration/config.yaml"
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration:/configuration"

  savingsplatform.dashboard-dapr:
    command: ["./daprd",
      "--app-id", "dapr-dashboard",
      "--app-port", "80",
      "--dapr-http-port", "3608",
      "--placement-host-address", "placement:50000",
      "--resources-path", "/components",
      "-config", "/configuration/config.yaml"
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration:/configuration"

  postgres:
    environment:
      - POSTGRES_PASSWORD=example
      - POSTGRES_USER=postgres
      - POSTGRES_DB=dapr-store

  postgrespay:
    environment:
      - POSTGRES_PASSWORD=example
      - POSTGRES_USER=postgres
      - POSTGRES_DB=payments-store

  placement:
    command: ["./placement", "-port", "50000", "-log-level", "debug"]
    ports:
      - "50000:50000"

  savingsplatform.paymentproxy-dapr:
    command: ["./daprd",
      "--app-id", "dapr-payment-proxy",
      "--app-port", "80",
      "--dapr-http-port", "3607",
      "--placement-host-address", "placement:50000",
      "--resources-path", "/components",
      "-config", "/configuration/config.yaml"
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration:/configuration"