version: '3.4'

services:
  zipkin:
    image: openzipkin/zipkin-slim
    ports:
      - "9411:9411"  # allows us to access the web console
  
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
    # AMQP protocol port
    - "5672:5672"
  
  placement:
    image: "daprio/dapr:1.12.2"
  
  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - "~/apps/postgres:/var/lib/postgresql/data"

  redis:
    image: redis:7.2.3
    hostname: statestoreredis
    ports:
      - "6379:6379"
    volumes:
      - ./redis-volume:/data

  savingsplatform.api:
    build:
      context: .
      dockerfile: ./SavingsPlatform.Api/Dockerfile
    depends_on:
     # - postgres
      - placement
      - rabbitmq 

  savingsplatform.api-dapr:
    image: "daprio/daprd:1.12.2"
    network_mode: "service:savingsplatform.api"
    depends_on:
      - savingsplatform.api

  savingsplatform.eventstore:
    build:
      context: .
      dockerfile: ./SavingsPlatform.EventStore/Dockerfile
    depends_on:
    #  - postgres
      - placement
      - rabbitmq 

  savingsplatform.eventstore-dapr:
    image: "daprio/daprd:1.12.2"
    network_mode: "service:savingsplatform.eventstore"
    depends_on:
      - savingsplatform.eventstore

  savingsplatform.paymentproxy:
    build:
      context: .
      dockerfile: ./SavingsPlatform.PaymentProxy/Dockerfile
    depends_on:
      - placement

  savingsplatform.paymentproxy-dapr:
    image: "daprio/daprd:1.12.2"
    network_mode: "service:savingsplatform.paymentproxy"
    depends_on:
      -  savingsplatform.paymentproxy

volumes:
  redis:
    driver: local

