version: '3.4'

services:
  savingsplatform.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - DAPR_HTTP_PORT=3605
      - SimulationConfig__SpeedMultiplier=1
      - NAMESPACE=savingsplatform
      - StateStore__StateStoreName=statestore-postgres 
    ports:
      - "5136:80"

  savingsplatform.eventstore:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - DAPR_HTTP_PORT=3606
      - ConnectionStrings__DocumentStore=host='host.docker.internal';username='postgres';password='example';port=5432;database='event-store'
      - DocumentStoreConfig__PlatformId=7a50b4e8-df1a-4253-b17d-0955e06fbe83
      - NAMESPACE=savingsplatform
    ports:
      - "5163:80"

  savingsplatform.paymentproxy:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - DAPR_HTTP_PORT=3607
      - NAMESPACE=payments
      - StateStore__StateStoreName=statestore-payments
    ports:
      - "5161:80"

  postgres:
    environment:
      - POSTGRES_PASSWORD=example
      - POSTGRES_USER=postgres
      - POSTGRES_DB=dapr-store
  
  savingsplatform.api-dapr:
    command: ["./daprd",
      "--app-id", "dapr-savings-acc",
      "--app-port", "80",
      "--dapr-http-port", "3605",
      "--placement-host-address", "placement:50000",
      "--resources-path", "/components",
      "-config", "/configuration/config.yaml"
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration:/configuration"
  
  savingsplatform.eventstore-dapr:
    command: ["./daprd",
      "--app-id", "dapr-savings-evt",
      "--app-port", "80",
      "--dapr-http-port", "3606",
      "--placement-host-address", "placement:50000",
      "--resources-path", "/components",
      "-config", "/configuration/config.yaml"
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration:/configuration"
  
  placement:
    command: ["./placement", "-port", "50000", "-log-level", "debug"]
    ports:
      - "50000:50000"
  
  redis:
    command: redis-server --appendonly yes --requirepass passw00rd
  
  savingsplatform.paymentproxy-dapr:
    command: ["./daprd",
      "--app-id", "dapr-payment-proxy",
      "--app-port", "80",
      "--dapr-http-port", "3607",
      "--placement-host-address", "placement:50000",
      "--resources-path", "/components",
      "-config", "/configuration/config.yaml"
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration:/configuration"