kind: ConfigMap
apiVersion: v1
metadata:
  name: savings-platform-postgres-cm
  namespace: {{ .Values.namespace }}
  labels:
    app: savings-platform-poc
    service: postgres
data:
  POSTGRES_PASSWORD: example
  POSTGRES_USER: postgres
  POSTGRES_DB: dapr-store

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: postgres
  namespace: {{ .Values.namespace }}
  labels:
    app: savings-platform-poc
    service: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      service: postgres
  template:
    metadata:
      labels:
        app: savings-platform-poc
        service: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:14-alpine
        imagePullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: 5432
            protocol: TCP
        envFrom:
          - configMapRef:
              name: savings-platform-postgres-cm

---

kind: Service
apiVersion: v1
metadata:
  name: postgres
  namespace: {{ .Values.namespace }}
  labels:
    app: savings-platform-poc
    service: postgres
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    service: postgres