apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore-payments
  namespace: payments
spec:
  type: state.redis
  version: v1
  initTimeout: '60s'
  metadata:
  - name: redisHost
    value: statestoreredis:6379
  - name: redisPassword
    value: "passw00rd"
  - name: timeoutInSeconds
    value: 60
scopes:
- dapr-payment-proxy