apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore-payments
  namespace: payments
spec:
  type: state.postgresql
  version: v1
  initTimeout: "75s"
  metadata:
  # Connection string
  - name: connectionString
    value: "host=postgrespay user=postgres password=example port=5432 connect_timeout=65 database=payments-store"
  # Timeout for database operations, in seconds (optional)
  - name: timeoutInSeconds
    value: 60
  # Uncomment this if you wish to use PostgreSQL as a state store for actors (optional)
  - name: actorStateStore
    value: "false"
scopes:
- dapr-payment-proxy